services:
  grafana:
    image: grafana/grafana:latest
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana
    networks:
      - grafana

networks:
  grafana:
