services:
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    #      - REDIS_PASSWORD=my_master_password
    volumes:
      - redis_data:/data/redis
    networks:
      - redis

  redis-replica:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
    #      - REDIS_MASTER_PASSWORD=my_master_password
    #      - REDIS_PASSWORD=my_replica_password
    networks:
      - redis
    volumes:
      - redis_data:/data/redis

volumes:
  redis_data:
#    external: true

networks:
  redis: